content:
  - name: paintings
    label: Paintings
    type: collection
    path: data/paintings.json
    format: json
    fields:
      - name: title
        label: Painting Title
        type: string
      - name: src
        label: Painting Image
        type: image
        path: images/
      - name: artist
        label: Artist
        type: string
        default: Ian Cocks
      - name: medium
        label: Medium
        type: string
      - name: year
        label: Year
        type: string
      - name: details
        label: Availability (e.g., Original - Sold)
        type: string
      - name: location
        label: Location
        type: string
      - name: imageSize
        label: Image Dimensions
        type: string
      - name: totalSize
        label: Total Dimensions (incl. border)
        type: string
      - name: edition
        label: Edition
        type: string
      - name: printedBy
        label: Printed By
        type: string
        default: Artful Images
      - name: printingDetails
        label: Printing Details (Long text)
        type: text
      - name: prices
        label: Prices
        type: object
        fields:
          - name: half
            label: Giclée Half Size Price
            type: string
          - name: full
            label: Giclée Full Size Price
            type: string
          - name: canvasHalf
            label: Canvas Half Size Price
            type: string
          - name: canvasFull
            label: Canvas Full Size Price
            type: string
      - name: id
        label: Unique ID (Number)
        type: number
      - name: size
        label: Thumbnail Size (Legacy)
        type: string
